### ISSUE TITLE
Modul "redet" zu viel.

### ISSUE THREAD

**Issue by RettungsTim** [RettungsTim/fhem-rollo#3]
Das Modul redet noch ein bisschen viel. Jeden abend und morgen habe ich folgendes im Log:

> 2016.07.13 21:17:28 1: cmd:closed | arg:
> 2016.07.13 21:17:28 1: desired_position = 100
> 2016.07.13 21:17:28 3: CUL_HM set OG_kz_RO_mi_RUNTER on
> 2016.07.13 21:17:28 3: CUL_HM set OG_kz_RO_mi_HOCH off
> 2016.07.13 21:17:28 1: General 100-0
> 2016.07.13 21:17:28 1: General 100-0
> 2016.07.13 21:17:29 1: General 0-0
> 2016.07.13 21:17:29 1: General 0-0
> 2016.07.13 21:17:33 1: cmd:closed | arg:
> 2016.07.13 21:17:33 1: desired_position = 100
> 2016.07.13 21:17:33 3: CUL_HM set OG_sz_RO_mi_RUNTER on
> 2016.07.13 21:17:33 3: CUL_HM set OG_sz_RO_mi_HOCH off
> 2016.07.13 21:17:34 1: General 100-0
> 2016.07.13 21:17:34 1: General 100-0
> 2016.07.13 21:17:34 1: General 0-0
> 2016.07.13 21:17:34 1: General 0-0
> 2016.07.13 21:17:37 1: cmd:closed | arg:
> 2016.07.13 21:17:37 1: desired_position = 100
> 2016.07.13 21:17:37 3: CUL_HM set EG_wz_RO_li_RUNTER on
> 2016.07.13 21:17:38 3: CUL_HM set EG_wz_RO_li_HOCH off
> 2016.07.13 21:17:38 1: General 0-0
> 2016.07.13 21:17:38 1: General 0-0
> 2016.07.13 21:17:38 3: CUL_HM EG_wz_RO_li_RUNTER repeat, level 00 instead of C8
> 2016.07.13 21:17:38 1: General 0-0
> 2016.07.13 21:17:38 1: General 0-0
> 2016.07.13 21:17:39 1: General 100-0
> 2016.07.13 21:17:39 1: General 100-0
> 2016.07.13 21:17:43 1: cmd:closed | arg:
> 2016.07.13 21:17:43 1: desired_position = 100
> 2016.07.13 21:17:43 3: CUL_HM set EG_wz_RO_re_RUNTER on
> 2016.07.13 21:17:43 3: CUL_HM set EG_wz_RO_re_HOCH off
> 2016.07.13 21:17:43 1: General 0-0
> 2016.07.13 21:17:43 1: General 0-0
> 2016.07.13 21:17:43 3: CUL_HM EG_wz_RO_re_RUNTER repeat, level 00 instead of C8
> 2016.07.13 21:17:44 1: General 0-0
> 2016.07.13 21:17:44 1: General 0-0
> 2016.07.13 21:17:44 1: General 100-0
> 2016.07.13 21:17:44 1: General 100-0
> 2016.07.13 21:17:47 1: cmd:closed | arg:
> 2016.07.13 21:17:47 1: desired_position = 100
> 2016.07.13 21:17:47 3: CUL_HM set EG_ez_RO_mi_RUNTER on
> 2016.07.13 21:17:47 3: CUL_HM set EG_ez_RO_mi_HOCH off
> 2016.07.13 21:17:48 1: General 0-0
> 2016.07.13 21:17:48 1: General 0-0
> 2016.07.13 21:17:48 3: CUL_HM EG_ez_RO_mi_RUNTER repeat, level 00 instead of C8
> 2016.07.13 21:17:48 1: General 0-0
> 2016.07.13 21:17:48 1: General 0-0
> 2016.07.13 21:17:48 1: General 100-0
> 2016.07.13 21:17:48 1: General 100-0
> 2016.07.13 21:17:52 1: cmd:closed | arg:
> 2016.07.13 21:17:52 1: desired_position = 100
> 2016.07.13 21:17:52 3: CUL_HM set EG_ku_RO_mi_RUNTER on
> 2016.07.13 21:17:52 3: CUL_HM set EG_ku_RO_mi_HOCH off
> 2016.07.13 21:17:53 1: General 0-0
> 2016.07.13 21:17:53 1: General 0-0
> 2016.07.13 21:17:53 3: CUL_HM EG_ku_RO_mi_RUNTER repeat, level 00 instead of C8
> 2016.07.13 21:17:53 1: General 0-0
> 2016.07.13 21:17:53 1: General 0-0
> 2016.07.13 21:17:53 1: General 100-0
> 2016.07.13 21:17:53 1: General 100-0
> 2016.07.13 21:17:56 3: Stopaufruf 6
> 2016.07.13 21:17:56 3: CUL_HM set OG_kz_RO_mi_RUNTER off
> 2016.07.13 21:17:56 1: General 0-0
> 2016.07.13 21:17:56 1: General 0-0
> 2016.07.13 21:17:57 1: cmd:closed | arg:
> 2016.07.13 21:17:57 1: desired_position = 100
> 2016.07.13 21:17:57 3: CUL_HM set EG_wc_RO_mi_RUNTER on
> 2016.07.13 21:17:57 3: CUL_HM set EG_wc_RO_mi_HOCH off
> 2016.07.13 21:17:58 1: General 0-0
> 2016.07.13 21:17:58 1: General 0-0
> 2016.07.13 21:17:58 3: CUL_HM EG_wc_RO_mi_RUNTER repeat, level 00 instead of C8
> 2016.07.13 21:17:58 1: General 0-0
> 2016.07.13 21:17:58 1: General 0-0
> 2016.07.13 21:17:59 1: General 100-0
> 2016.07.13 21:17:59 1: General 100-0
> 2016.07.13 21:18:00 3: Stopaufruf 6
> 2016.07.13 21:18:00 3: CUL_HM set EG_wz_RO_li_RUNTER off
> 2016.07.13 21:18:00 1: General 0-0
> 2016.07.13 21:18:00 1: General 0-0
> 2016.07.13 21:18:01 3: Stopaufruf 6
> 2016.07.13 21:18:01 3: CUL_HM set OG_sz_RO_mi_RUNTER off
> 2016.07.13 21:18:01 1: General 0-0
> 2016.07.13 21:18:01 1: General 0-0
> 2016.07.13 21:18:05 3: Stopaufruf 6
> 2016.07.13 21:18:05 3: CUL_HM set EG_wz_RO_re_RUNTER off
> 2016.07.13 21:18:05 1: General 0-0
> 2016.07.13 21:18:05 1: General 0-0
> 2016.07.13 21:18:13 3: Stopaufruf 6
> 2016.07.13 21:18:13 3: CUL_HM set EG_wc_RO_mi_RUNTER off
> 2016.07.13 21:18:13 1: General 0-0
> 2016.07.13 21:18:13 1: General 0-0
> 2016.07.13 21:18:14 3: Stopaufruf 6
> 2016.07.13 21:18:14 3: CUL_HM set EG_ku_RO_mi_RUNTER off
> 2016.07.13 21:18:14 1: General 0-0
> 2016.07.13 21:18:14 1: General 0-0
> 2016.07.13 21:18:15 3: Stopaufruf 6
> 2016.07.13 21:18:15 3: CUL_HM set EG_ez_RO_mi_RUNTER off
> 2016.07.13 21:18:15 1: General 0-0
> 2016.07.13 21:18:15 1: General 0-0

**Comment by thomasramm** [comment]
Ja, ist mir auch schon aufgefallen, so lange aber das Modul so "unstabil" war wollte ich das nicht ändern, da es bei der Fehlersuche recht gut unterstützt hat.
Habe jetzt die Logmeldung folgendermaßen gestaffelt:

**Debug Level 5**
Ausgabe von "Starte Subroutine XY"
**Debug Level 4**
Ausgabe einiger Parameter und Berechnungsergebnisse
**Debug Level 3**
Warnhinweise, bei denen aber trotzdem alles Fehlerfrei funktioniert
**Debug Level 2**
Fehlermeldungen, jetzt hat irgendetwas wahrscheinlich nicht geklappt
**Debug Level 1**
keine Meldungen! - "silent Mode", auch keine Fehlermeldungen

insgesamt gibt es im Modul 32 potenzielle Log-Meldungen, wobei es teilweise noch recht große Blöcke ohne jeglichen Hinweis gibt, würde ich aber warten bis eine Notwendigkeit besteht diese besser zu debuggen.
